[project]
name = "calendar-reader"
version = "0.1.0"
description = "Reads events from an ICS calendar within a date range"
readme = "README.md"
authors = [
    { name = "Raul Alegre", email = "raul.alemar@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "icalendar>=7.3.0",
    "pandas>=3.0.6",
    "streamlit>=1.64.0",
    "streamlit-aggrid>=1.2.1.post2",
    "typesafe-sdk>=0.7.0",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"


[tool.uv]
preview-features = ["centralized-project-envs"]
