[project]
name = "calendar-reader"
version = "0.1.0"
description = "Lee eventos de un calendario en formato ICS dentro de un rango de fechas"
readme = "README.md"
authors = [
    { name = "Raul Alegre", email = "raul.alemar@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "icalendar>=7.3.0",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"


[tool.uv]
preview-features = ["centralized-project-envs"]
